-- Profile self-service and updated operational role matrix.
delete from public.role_permissions rp using public.roles ro, public.resources r where rp.role_id=ro.id and rp.resource_id=r.id and ro.key in ('gatesec','checker') and r.key in ('dashboard','history','wh_in','queue_parking','start_loading','finish_loading','wh_out','live_view','master_data','user_role');
insert into public.role_permissions(role_id,resource_id,permission_id) select ro.id,r.id,p.id from public.roles ro join public.resources r on r.key in ('queue_parking','start_loading','finish_loading','history') join public.permissions p on ((r.key='queue_parking' and p.key='view') or (r.key='start_loading' and p.key in ('view','update','upload')) or (r.key='finish_loading' and p.key in ('view','update','upload')) or (r.key='history' and p.key='view')) where ro.key='checker';
insert into public.role_permissions(role_id,resource_id,permission_id) select ro.id,r.id,p.id from public.roles ro join public.resources r on r.key in ('wh_in','queue_parking','wh_out','history') join public.permissions p on ((r.key='wh_in' and p.key in ('view','create','update','upload')) or (r.key='queue_parking' and p.key in ('view','update')) or (r.key='wh_out' and p.key in ('view','update')) or (r.key='history' and p.key in ('view','update','delete'))) where ro.key='gatesec';
drop policy if exists "loading photo records require matching permission and visit status" on public.photos;
create policy "photo records require matching workflow permission" on public.photos for insert to authenticated with check (uploaded_by=(select auth.uid()) and ((photo_type='registration'::public.photo_type and (select private.has_permission('wh_in','upload')) and exists(select 1 from public.visits v where v.id=photos.visit_id and v.process_status in ('wh_in','registered'))) or (photo_type='loading_start'::public.photo_type and (select private.has_permission('start_loading','upload')) and exists(select 1 from public.visits v where v.id=photos.visit_id and v.process_status in ('registered','queue','started'))) or (photo_type='loading_completion'::public.photo_type and (select private.has_permission('finish_loading','upload')) and exists(select 1 from public.visits v where v.id=photos.visit_id and v.process_status in ('started','completed')))));
drop policy if exists "checker and admin can upload visit photos" on storage.objects;
create policy "authorized roles can upload visit photos" on storage.objects for insert to authenticated with check (bucket_id='trcm-visit-photos' and ((select private.has_permission('wh_in','upload')) or (select private.has_permission('start_loading','upload')) or (select private.has_permission('finish_loading','upload'))) and (storage.foldername(name))[1] in (select v.id::text from public.visits v));
drop policy if exists "operational roles can view visit photos" on storage.objects;
create policy "operational roles can view visit photos" on storage.objects for select to authenticated using (bucket_id='trcm-visit-photos' and ((select private.has_permission('wh_in','view')) or (select private.has_permission('start_loading','view')) or (select private.has_permission('finish_loading','view'))));
